/*
* Copyright 2006-2007 Javector Software LLC
*
* Licensed under the GNU General Public License, Version 2 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.gnu.org/copyleft/gpl.html
*
* THE SOURCE CODE AND ACCOMPANYING FILES ARE PROVIDED WITHOUT ANY WARRANTY,
* WRITTEN OR IMPLIED.
*
* The copyright holder provides this software under other licenses for those
* wishing to include it with products or systems not licensed under the GPL.
* Contact licenses@javector.com for more information.
*/
package ebay.apis.eblbasecomponents;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.1-hudson-1368-EA3
 * Generated source version: 2.1
 * 
 */
@WebService(name = "eBayAPIInterface", targetNamespace = "urn:ebay:apis:eBLBaseComponents")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso( { ObjectFactory.class })
public interface EBayAPIInterface {

  /**
   * 
   * @param addDisputeRequest
   * @return returns ebay.apis.eblbasecomponents.AddDisputeResponseType
   */
  @WebMethod(operationName = "AddDispute")
  @WebResult(name = "AddDisputeResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddDisputeResponse")
  public AddDisputeResponseType addDispute(
      @WebParam(name = "AddDisputeRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddDisputeRequest")
      AddDisputeRequestType addDisputeRequest);

  /**
   * 
   * @param addDisputeResponseRequest
   * @return returns ebay.apis.eblbasecomponents.AddDisputeResponseResponseType
   */
  @WebMethod(operationName = "AddDisputeResponse")
  @WebResult(name = "AddDisputeResponseResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddDisputeResponseResponse")
  public AddDisputeResponseResponseType addDisputeResponse(
      @WebParam(name = "AddDisputeResponseRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddDisputeResponseRequest")
      AddDisputeResponseRequestType addDisputeResponseRequest);

  /**
   * 
   * @param addItemRequest
   * @return returns ebay.apis.eblbasecomponents.AddItemResponseType
   */
  @WebMethod(operationName = "AddItem")
  @WebResult(name = "AddItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddItemResponse")
  public AddItemResponseType addItem(
      @WebParam(name = "AddItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddItemRequest")
      AddItemRequestType addItemRequest);

  /**
   * 
   * @param addLiveAuctionItemRequest
   * @return returns ebay.apis.eblbasecomponents.AddLiveAuctionItemResponseType
   */
  @WebMethod(operationName = "AddLiveAuctionItem")
  @WebResult(name = "AddLiveAuctionItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddLiveAuctionItemResponse")
  public AddLiveAuctionItemResponseType addLiveAuctionItem(
      @WebParam(name = "AddLiveAuctionItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddLiveAuctionItemRequest")
      AddLiveAuctionItemRequestType addLiveAuctionItemRequest);

  /**
   * 
   * @param addMemberMessageRequest
   * @return returns ebay.apis.eblbasecomponents.AddMemberMessageResponseType
   */
  @WebMethod(operationName = "AddMemberMessage")
  @WebResult(name = "AddMemberMessageResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageResponse")
  public AddMemberMessageResponseType addMemberMessage(
      @WebParam(name = "AddMemberMessageRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageRequest")
      AddMemberMessageRequestType addMemberMessageRequest);

  /**
   * 
   * @param addMemberMessageAAQToPartnerRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.AddMemberMessageAAQToPartnerResponseType
   */
  @WebMethod(operationName = "AddMemberMessageAAQToPartner")
  @WebResult(name = "AddMemberMessageAAQToPartnerResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageAAQToPartnerResponse")
  public AddMemberMessageAAQToPartnerResponseType addMemberMessageAAQToPartner(
      @WebParam(name = "AddMemberMessageAAQToPartnerRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageAAQToPartnerRequest")
      AddMemberMessageAAQToPartnerRequestType addMemberMessageAAQToPartnerRequest);

  /**
   * 
   * @param addMemberMessageRTQRequest
   * @return returns ebay.apis.eblbasecomponents.AddMemberMessageRTQResponseType
   */
  @WebMethod(operationName = "AddMemberMessageRTQ")
  @WebResult(name = "AddMemberMessageRTQResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageRTQResponse")
  public AddMemberMessageRTQResponseType addMemberMessageRTQ(
      @WebParam(name = "AddMemberMessageRTQRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessageRTQRequest")
      AddMemberMessageRTQRequestType addMemberMessageRTQRequest);

  /**
   * 
   * @param addMemberMessagesAAQToBidderRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.AddMemberMessagesAAQToBidderResponseType
   */
  @WebMethod(operationName = "AddMemberMessagesAAQToBidder")
  @WebResult(name = "AddMemberMessagesAAQToBidderResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessagesAAQToBidderResponse")
  public AddMemberMessagesAAQToBidderResponseType addMemberMessagesAAQToBidder(
      @WebParam(name = "AddMemberMessagesAAQToBidderRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddMemberMessagesAAQToBidderRequest")
      AddMemberMessagesAAQToBidderRequestType addMemberMessagesAAQToBidderRequest);

  /**
   * 
   * @param addOrderRequest
   * @return returns ebay.apis.eblbasecomponents.AddOrderResponseType
   */
  @WebMethod(operationName = "AddOrder")
  @WebResult(name = "AddOrderResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddOrderResponse")
  public AddOrderResponseType addOrder(
      @WebParam(name = "AddOrderRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddOrderRequest")
      AddOrderRequestType addOrderRequest);

  /**
   * 
   * @param addSecondChanceItemRequest
   * @return returns ebay.apis.eblbasecomponents.AddSecondChanceItemResponseType
   */
  @WebMethod(operationName = "AddSecondChanceItem")
  @WebResult(name = "AddSecondChanceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddSecondChanceItemResponse")
  public AddSecondChanceItemResponseType addSecondChanceItem(
      @WebParam(name = "AddSecondChanceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddSecondChanceItemRequest")
      AddSecondChanceItemRequestType addSecondChanceItemRequest);

  /**
   * 
   * @param addToItemDescriptionRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.AddToItemDescriptionResponseType
   */
  @WebMethod(operationName = "AddToItemDescription")
  @WebResult(name = "AddToItemDescriptionResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToItemDescriptionResponse")
  public AddToItemDescriptionResponseType addToItemDescription(
      @WebParam(name = "AddToItemDescriptionRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToItemDescriptionRequest")
      AddToItemDescriptionRequestType addToItemDescriptionRequest);

  /**
   * 
   * @param addToWatchListRequest
   * @return returns ebay.apis.eblbasecomponents.AddToWatchListResponseType
   */
  @WebMethod(operationName = "AddToWatchList")
  @WebResult(name = "AddToWatchListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToWatchListResponse")
  public AddToWatchListResponseType addToWatchList(
      @WebParam(name = "AddToWatchListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddToWatchListRequest")
      AddToWatchListRequestType addToWatchListRequest);

  /**
   * 
   * @param addTransactionConfirmationItemRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.AddTransactionConfirmationItemResponseType
   */
  @WebMethod(operationName = "AddTransactionConfirmationItem")
  @WebResult(name = "AddTransactionConfirmationItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddTransactionConfirmationItemResponse")
  public AddTransactionConfirmationItemResponseType addTransactionConfirmationItem(
      @WebParam(name = "AddTransactionConfirmationItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "AddTransactionConfirmationItemRequest")
      AddTransactionConfirmationItemRequestType addTransactionConfirmationItemRequest);

  /**
   * 
   * @param approveLiveAuctionBiddersRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.ApproveLiveAuctionBiddersResponseType
   */
  @WebMethod(operationName = "ApproveLiveAuctionBidders")
  @WebResult(name = "ApproveLiveAuctionBiddersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ApproveLiveAuctionBiddersResponse")
  public ApproveLiveAuctionBiddersResponseType approveLiveAuctionBidders(
      @WebParam(name = "ApproveLiveAuctionBiddersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ApproveLiveAuctionBiddersRequest")
      ApproveLiveAuctionBiddersRequestType approveLiveAuctionBiddersRequest);

  /**
   * 
   * @param completeSaleRequest
   * @return returns ebay.apis.eblbasecomponents.CompleteSaleResponseType
   */
  @WebMethod(operationName = "CompleteSale")
  @WebResult(name = "CompleteSaleResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "CompleteSaleResponse")
  public CompleteSaleResponseType completeSale(
      @WebParam(name = "CompleteSaleRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "CompleteSaleRequest")
      CompleteSaleRequestType completeSaleRequest);

  /**
   * 
   * @param deleteMyMessagesRequest
   * @return returns ebay.apis.eblbasecomponents.DeleteMyMessagesResponseType
   */
  @WebMethod(operationName = "DeleteMyMessages")
  @WebResult(name = "DeleteMyMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "DeleteMyMessagesResponse")
  public DeleteMyMessagesResponseType deleteMyMessages(
      @WebParam(name = "DeleteMyMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "DeleteMyMessagesRequest")
      DeleteMyMessagesRequestType deleteMyMessagesRequest);

  /**
   * 
   * @param endItemRequest
   * @return returns ebay.apis.eblbasecomponents.EndItemResponseType
   */
  @WebMethod(operationName = "EndItem")
  @WebResult(name = "EndItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndItemResponse")
  public EndItemResponseType endItem(
      @WebParam(name = "EndItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "EndItemRequest")
      EndItemRequestType endItemRequest);

  /**
   * 
   * @param fetchTokenRequest
   * @return returns ebay.apis.eblbasecomponents.FetchTokenResponseType
   */
  @WebMethod(operationName = "FetchToken")
  @WebResult(name = "FetchTokenResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "FetchTokenResponse")
  public FetchTokenResponseType fetchToken(
      @WebParam(name = "FetchTokenRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "FetchTokenRequest")
      FetchTokenRequestType fetchTokenRequest);

  /**
   * 
   * @param getAccountRequest
   * @return returns ebay.apis.eblbasecomponents.GetAccountResponseType
   */
  @WebMethod(operationName = "GetAccount")
  @WebResult(name = "GetAccountResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAccountResponse")
  public GetAccountResponseType getAccount(
      @WebParam(name = "GetAccountRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAccountRequest")
      GetAccountRequestType getAccountRequest);

  /**
   * 
   * @param getAdFormatLeadsRequest
   * @return returns ebay.apis.eblbasecomponents.GetAdFormatLeadsResponseType
   */
  @WebMethod(operationName = "GetAdFormatLeads")
  @WebResult(name = "GetAdFormatLeadsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAdFormatLeadsResponse")
  public GetAdFormatLeadsResponseType getAdFormatLeads(
      @WebParam(name = "GetAdFormatLeadsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAdFormatLeadsRequest")
      GetAdFormatLeadsRequestType getAdFormatLeadsRequest);

  /**
   * 
   * @param getAllBiddersRequest
   * @return returns ebay.apis.eblbasecomponents.GetAllBiddersResponseType
   */
  @WebMethod(operationName = "GetAllBidders")
  @WebResult(name = "GetAllBiddersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAllBiddersResponse")
  public GetAllBiddersResponseType getAllBidders(
      @WebParam(name = "GetAllBiddersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAllBiddersRequest")
      GetAllBiddersRequestType getAllBiddersRequest);

  /**
   * 
   * @param getApiAccessRulesRequest
   * @return returns ebay.apis.eblbasecomponents.GetApiAccessRulesResponseType
   */
  @WebMethod(operationName = "GetApiAccessRules")
  @WebResult(name = "GetApiAccessRulesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetApiAccessRulesResponse")
  public GetApiAccessRulesResponseType getApiAccessRules(
      @WebParam(name = "GetApiAccessRulesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetApiAccessRulesRequest")
      GetApiAccessRulesRequestType getApiAccessRulesRequest);

  /**
   * 
   * @param getAttributesCSRequest
   * @return returns ebay.apis.eblbasecomponents.GetAttributesCSResponseType
   */
  @WebMethod(operationName = "GetAttributesCS")
  @WebResult(name = "GetAttributesCSResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAttributesCSResponse")
  public GetAttributesCSResponseType getAttributesCS(
      @WebParam(name = "GetAttributesCSRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAttributesCSRequest")
      GetAttributesCSRequestType getAttributesCSRequest);

  /**
   * 
   * @param getAttributesXSLRequest
   * @return returns ebay.apis.eblbasecomponents.GetAttributesXSLResponseType
   */
  @WebMethod(operationName = "GetAttributesXSL")
  @WebResult(name = "GetAttributesXSLResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAttributesXSLResponse")
  public GetAttributesXSLResponseType getAttributesXSL(
      @WebParam(name = "GetAttributesXSLRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetAttributesXSLRequest")
      GetAttributesXSLRequestType getAttributesXSLRequest);

  /**
   * 
   * @param getBestOffersRequest
   * @return returns ebay.apis.eblbasecomponents.GetBestOffersResponseType
   */
  @WebMethod(operationName = "GetBestOffers")
  @WebResult(name = "GetBestOffersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBestOffersResponse")
  public GetBestOffersResponseType getBestOffers(
      @WebParam(name = "GetBestOffersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBestOffersRequest")
      GetBestOffersRequestType getBestOffersRequest);

  /**
   * 
   * @param getBidderListRequest
   * @return returns ebay.apis.eblbasecomponents.GetBidderListResponseType
   */
  @WebMethod(operationName = "GetBidderList")
  @WebResult(name = "GetBidderListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBidderListResponse")
  public GetBidderListResponseType getBidderList(
      @WebParam(name = "GetBidderListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetBidderListRequest")
      GetBidderListRequestType getBidderListRequest);

  /**
   * 
   * @param getCategoriesRequest
   * @return returns ebay.apis.eblbasecomponents.GetCategoriesResponseType
   */
  @WebMethod(operationName = "GetCategories")
  @WebResult(name = "GetCategoriesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoriesResponse")
  public GetCategoriesResponseType getCategories(
      @WebParam(name = "GetCategoriesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoriesRequest")
      GetCategoriesRequestType getCategoriesRequest);

  /**
   * 
   * @param getCategory2CSRequest
   * @return returns ebay.apis.eblbasecomponents.GetCategory2CSResponseType
   */
  @WebMethod(operationName = "GetCategory2CS")
  @WebResult(name = "GetCategory2CSResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategory2CSResponse")
  public GetCategory2CSResponseType getCategory2CS(
      @WebParam(name = "GetCategory2CSRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategory2CSRequest")
      GetCategory2CSRequestType getCategory2CSRequest);

  /**
   * 
   * @param getCategory2FinanceOfferRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetCategory2FinanceOfferResponseType
   */
  @WebMethod(operationName = "GetCategory2FinanceOffer")
  @WebResult(name = "GetCategory2FinanceOfferResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategory2FinanceOfferResponse")
  public GetCategory2FinanceOfferResponseType getCategory2FinanceOffer(
      @WebParam(name = "GetCategory2FinanceOfferRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategory2FinanceOfferRequest")
      GetCategory2FinanceOfferRequestType getCategory2FinanceOfferRequest);

  /**
   * 
   * @param getCategoryFeaturesRequest
   * @return returns ebay.apis.eblbasecomponents.GetCategoryFeaturesResponseType
   */
  @WebMethod(operationName = "GetCategoryFeatures")
  @WebResult(name = "GetCategoryFeaturesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryFeaturesResponse")
  public GetCategoryFeaturesResponseType getCategoryFeatures(
      @WebParam(name = "GetCategoryFeaturesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryFeaturesRequest")
      GetCategoryFeaturesRequestType getCategoryFeaturesRequest);

  /**
   * 
   * @param getCategoryListingsRequest
   * @return returns ebay.apis.eblbasecomponents.GetCategoryListingsResponseType
   */
  @WebMethod(operationName = "GetCategoryListings")
  @WebResult(name = "GetCategoryListingsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryListingsResponse")
  public GetCategoryListingsResponseType getCategoryListings(
      @WebParam(name = "GetCategoryListingsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryListingsRequest")
      GetCategoryListingsRequestType getCategoryListingsRequest);

  /**
   * 
   * @param getCategoryMappingsRequest
   * @return returns ebay.apis.eblbasecomponents.GetCategoryMappingsResponseType
   */
  @WebMethod(operationName = "GetCategoryMappings")
  @WebResult(name = "GetCategoryMappingsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryMappingsResponse")
  public GetCategoryMappingsResponseType getCategoryMappings(
      @WebParam(name = "GetCategoryMappingsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCategoryMappingsRequest")
      GetCategoryMappingsRequestType getCategoryMappingsRequest);

  /**
   * 
   * @param getChallengeTokenRequest
   * @return returns ebay.apis.eblbasecomponents.GetChallengeTokenResponseType
   */
  @WebMethod(operationName = "GetChallengeToken")
  @WebResult(name = "GetChallengeTokenResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetChallengeTokenResponse")
  public GetChallengeTokenResponseType getChallengeToken(
      @WebParam(name = "GetChallengeTokenRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetChallengeTokenRequest")
      GetChallengeTokenRequestType getChallengeTokenRequest);

  /**
   * 
   * @param getCharitiesRequest
   * @return returns ebay.apis.eblbasecomponents.GetCharitiesResponseType
   */
  @WebMethod(operationName = "GetCharities")
  @WebResult(name = "GetCharitiesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCharitiesResponse")
  public GetCharitiesResponseType getCharities(
      @WebParam(name = "GetCharitiesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCharitiesRequest")
      GetCharitiesRequestType getCharitiesRequest);

  /**
   * 
   * @param getContextualKeywordsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetContextualKeywordsResponseType
   */
  @WebMethod(operationName = "GetContextualKeywords")
  @WebResult(name = "GetContextualKeywordsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetContextualKeywordsResponse")
  public GetContextualKeywordsResponseType getContextualKeywords(
      @WebParam(name = "GetContextualKeywordsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetContextualKeywordsRequest")
      GetContextualKeywordsRequestType getContextualKeywordsRequest);

  /**
   * 
   * @param getCrossPromotionsRequest
   * @return returns ebay.apis.eblbasecomponents.GetCrossPromotionsResponseType
   */
  @WebMethod(operationName = "GetCrossPromotions")
  @WebResult(name = "GetCrossPromotionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCrossPromotionsResponse")
  public GetCrossPromotionsResponseType getCrossPromotions(
      @WebParam(name = "GetCrossPromotionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetCrossPromotionsRequest")
      GetCrossPromotionsRequestType getCrossPromotionsRequest);

  /**
   * 
   * @param getDescriptionTemplatesRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetDescriptionTemplatesResponseType
   */
  @WebMethod(operationName = "GetDescriptionTemplates")
  @WebResult(name = "GetDescriptionTemplatesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetDescriptionTemplatesResponse")
  public GetDescriptionTemplatesResponseType getDescriptionTemplates(
      @WebParam(name = "GetDescriptionTemplatesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetDescriptionTemplatesRequest")
      GetDescriptionTemplatesRequestType getDescriptionTemplatesRequest);

  /**
   * 
   * @param getDisputeRequest
   * @return returns ebay.apis.eblbasecomponents.GetDisputeResponseType
   */
  @WebMethod(operationName = "GetDispute")
  @WebResult(name = "GetDisputeResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetDisputeResponse")
  public GetDisputeResponseType getDispute(
      @WebParam(name = "GetDisputeRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetDisputeRequest")
      GetDisputeRequestType getDisputeRequest);

  /**
   * 
   * @param getFeedbackRequest
   * @return returns ebay.apis.eblbasecomponents.GetFeedbackResponseType
   */
  @WebMethod(operationName = "GetFeedback")
  @WebResult(name = "GetFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetFeedbackResponse")
  public GetFeedbackResponseType getFeedback(
      @WebParam(name = "GetFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetFeedbackRequest")
      GetFeedbackRequestType getFeedbackRequest);

  /**
   * 
   * @param getFinanceOffersRequest
   * @return returns ebay.apis.eblbasecomponents.GetFinanceOffersResponseType
   */
  @WebMethod(operationName = "GetFinanceOffers")
  @WebResult(name = "GetFinanceOffersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetFinanceOffersResponse")
  public GetFinanceOffersResponseType getFinanceOffers(
      @WebParam(name = "GetFinanceOffersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetFinanceOffersRequest")
      GetFinanceOffersRequestType getFinanceOffersRequest);

  /**
   * 
   * @param getHighBiddersRequest
   * @return returns ebay.apis.eblbasecomponents.GetHighBiddersResponseType
   */
  @WebMethod(operationName = "GetHighBidders")
  @WebResult(name = "GetHighBiddersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetHighBiddersResponse")
  public GetHighBiddersResponseType getHighBidders(
      @WebParam(name = "GetHighBiddersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetHighBiddersRequest")
      GetHighBiddersRequestType getHighBiddersRequest);

  /**
   * 
   * @param getItemRequest
   * @return returns ebay.apis.eblbasecomponents.GetItemResponseType
   */
  @WebMethod(operationName = "GetItem")
  @WebResult(name = "GetItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemResponse")
  public GetItemResponseType getItem(
      @WebParam(name = "GetItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemRequest")
      GetItemRequestType getItemRequest);

  /**
   * 
   * @param getItemRecommendationsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetItemRecommendationsResponseType
   */
  @WebMethod(operationName = "GetItemRecommendations")
  @WebResult(name = "GetItemRecommendationsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemRecommendationsResponse")
  public GetItemRecommendationsResponseType getItemRecommendations(
      @WebParam(name = "GetItemRecommendationsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemRecommendationsRequest")
      GetItemRecommendationsRequestType getItemRecommendationsRequest);

  /**
   * 
   * @param getItemShippingRequest
   * @return returns ebay.apis.eblbasecomponents.GetItemShippingResponseType
   */
  @WebMethod(operationName = "GetItemShipping")
  @WebResult(name = "GetItemShippingResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemShippingResponse")
  public GetItemShippingResponseType getItemShipping(
      @WebParam(name = "GetItemShippingRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemShippingRequest")
      GetItemShippingRequestType getItemShippingRequest);

  /**
   * 
   * @param getItemTransactionsRequest
   * @return returns ebay.apis.eblbasecomponents.GetItemTransactionsResponseType
   */
  @WebMethod(operationName = "GetItemTransactions")
  @WebResult(name = "GetItemTransactionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemTransactionsResponse")
  public GetItemTransactionsResponseType getItemTransactions(
      @WebParam(name = "GetItemTransactionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemTransactionsRequest")
      GetItemTransactionsRequestType getItemTransactionsRequest);

  /**
   * 
   * @param getItemsAwaitingFeedbackRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetItemsAwaitingFeedbackResponseType
   */
  @WebMethod(operationName = "GetItemsAwaitingFeedback")
  @WebResult(name = "GetItemsAwaitingFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemsAwaitingFeedbackResponse")
  public GetItemsAwaitingFeedbackResponseType getItemsAwaitingFeedback(
      @WebParam(name = "GetItemsAwaitingFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetItemsAwaitingFeedbackRequest")
      GetItemsAwaitingFeedbackRequestType getItemsAwaitingFeedbackRequest);

  /**
   * 
   * @param getLiveAuctionBiddersRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetLiveAuctionBiddersResponseType
   */
  @WebMethod(operationName = "GetLiveAuctionBidders")
  @WebResult(name = "GetLiveAuctionBiddersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetLiveAuctionBiddersResponse")
  public GetLiveAuctionBiddersResponseType getLiveAuctionBidders(
      @WebParam(name = "GetLiveAuctionBiddersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetLiveAuctionBiddersRequest")
      GetLiveAuctionBiddersRequestType getLiveAuctionBiddersRequest);

  /**
   * 
   * @param getLiveAuctionCatalogDetailsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetLiveAuctionCatalogDetailsResponseType
   */
  @WebMethod(operationName = "GetLiveAuctionCatalogDetails")
  @WebResult(name = "GetLiveAuctionCatalogDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetLiveAuctionCatalogDetailsResponse")
  public GetLiveAuctionCatalogDetailsResponseType getLiveAuctionCatalogDetails(
      @WebParam(name = "GetLiveAuctionCatalogDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetLiveAuctionCatalogDetailsRequest")
      GetLiveAuctionCatalogDetailsRequestType getLiveAuctionCatalogDetailsRequest);

  /**
   * 
   * @param getMemberMessagesRequest
   * @return returns ebay.apis.eblbasecomponents.GetMemberMessagesResponseType
   */
  @WebMethod(operationName = "GetMemberMessages")
  @WebResult(name = "GetMemberMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMemberMessagesResponse")
  public GetMemberMessagesResponseType getMemberMessages(
      @WebParam(name = "GetMemberMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMemberMessagesRequest")
      GetMemberMessagesRequestType getMemberMessagesRequest);

  /**
   * 
   * @param getMyMessagesRequest
   * @return returns ebay.apis.eblbasecomponents.GetMyMessagesResponseType
   */
  @WebMethod(operationName = "GetMyMessages")
  @WebResult(name = "GetMyMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyMessagesResponse")
  public GetMyMessagesResponseType getMyMessages(
      @WebParam(name = "GetMyMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyMessagesRequest")
      GetMyMessagesRequestType getMyMessagesRequest);

  /**
   * 
   * @param getMyeBayRequest
   * @return returns ebay.apis.eblbasecomponents.GetMyeBayResponseType
   */
  @WebMethod(operationName = "GetMyeBay")
  @WebResult(name = "GetMyeBayResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayResponse")
  public GetMyeBayResponseType getMyeBay(
      @WebParam(name = "GetMyeBayRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayRequest")
      GetMyeBayRequestType getMyeBayRequest);

  /**
   * 
   * @param getMyeBayBuyingRequest
   * @return returns ebay.apis.eblbasecomponents.GetMyeBayBuyingResponseType
   */
  @WebMethod(operationName = "GetMyeBayBuying")
  @WebResult(name = "GetMyeBayBuyingResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayBuyingResponse")
  public GetMyeBayBuyingResponseType getMyeBayBuying(
      @WebParam(name = "GetMyeBayBuyingRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayBuyingRequest")
      GetMyeBayBuyingRequestType getMyeBayBuyingRequest);

  /**
   * 
   * @param getMyeBayRemindersRequest
   * @return returns ebay.apis.eblbasecomponents.GetMyeBayRemindersResponseType
   */
  @WebMethod(operationName = "GetMyeBayReminders")
  @WebResult(name = "GetMyeBayRemindersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayRemindersResponse")
  public GetMyeBayRemindersResponseType getMyeBayReminders(
      @WebParam(name = "GetMyeBayRemindersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBayRemindersRequest")
      GetMyeBayRemindersRequestType getMyeBayRemindersRequest);

  /**
   * 
   * @param getMyeBaySellingRequest
   * @return returns ebay.apis.eblbasecomponents.GetMyeBaySellingResponseType
   */
  @WebMethod(operationName = "GetMyeBaySelling")
  @WebResult(name = "GetMyeBaySellingResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBaySellingResponse")
  public GetMyeBaySellingResponseType getMyeBaySelling(
      @WebParam(name = "GetMyeBaySellingRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetMyeBaySellingRequest")
      GetMyeBaySellingRequestType getMyeBaySellingRequest);

  /**
   * 
   * @param getNotificationPreferencesRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetNotificationPreferencesResponseType
   */
  @WebMethod(operationName = "GetNotificationPreferences")
  @WebResult(name = "GetNotificationPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationPreferencesResponse")
  public GetNotificationPreferencesResponseType getNotificationPreferences(
      @WebParam(name = "GetNotificationPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationPreferencesRequest")
      GetNotificationPreferencesRequestType getNotificationPreferencesRequest);

  /**
   * 
   * @param getNotificationsUsageRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetNotificationsUsageResponseType
   */
  @WebMethod(operationName = "GetNotificationsUsage")
  @WebResult(name = "GetNotificationsUsageResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationsUsageResponse")
  public GetNotificationsUsageResponseType getNotificationsUsage(
      @WebParam(name = "GetNotificationsUsageRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetNotificationsUsageRequest")
      GetNotificationsUsageRequestType getNotificationsUsageRequest);

  /**
   * 
   * @param getOrderTransactionsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetOrderTransactionsResponseType
   */
  @WebMethod(operationName = "GetOrderTransactions")
  @WebResult(name = "GetOrderTransactionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetOrderTransactionsResponse")
  public GetOrderTransactionsResponseType getOrderTransactions(
      @WebParam(name = "GetOrderTransactionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetOrderTransactionsRequest")
      GetOrderTransactionsRequestType getOrderTransactionsRequest);

  /**
   * 
   * @param getOrdersRequest
   * @return returns ebay.apis.eblbasecomponents.GetOrdersResponseType
   */
  @WebMethod(operationName = "GetOrders")
  @WebResult(name = "GetOrdersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetOrdersResponse")
  public GetOrdersResponseType getOrders(
      @WebParam(name = "GetOrdersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetOrdersRequest")
      GetOrdersRequestType getOrdersRequest);

  /**
   * 
   * @param getPictureManagerDetailsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetPictureManagerDetailsResponseType
   */
  @WebMethod(operationName = "GetPictureManagerDetails")
  @WebResult(name = "GetPictureManagerDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPictureManagerDetailsResponse")
  public GetPictureManagerDetailsResponseType getPictureManagerDetails(
      @WebParam(name = "GetPictureManagerDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPictureManagerDetailsRequest")
      GetPictureManagerDetailsRequestType getPictureManagerDetailsRequest);

  /**
   * 
   * @param getPictureManagerOptionsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetPictureManagerOptionsResponseType
   */
  @WebMethod(operationName = "GetPictureManagerOptions")
  @WebResult(name = "GetPictureManagerOptionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPictureManagerOptionsResponse")
  public GetPictureManagerOptionsResponseType getPictureManagerOptions(
      @WebParam(name = "GetPictureManagerOptionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPictureManagerOptionsRequest")
      GetPictureManagerOptionsRequestType getPictureManagerOptionsRequest);

  /**
   * 
   * @param getPopularKeywordsRequest
   * @return returns ebay.apis.eblbasecomponents.GetPopularKeywordsResponseType
   */
  @WebMethod(operationName = "GetPopularKeywords")
  @WebResult(name = "GetPopularKeywordsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPopularKeywordsResponse")
  public GetPopularKeywordsResponseType getPopularKeywords(
      @WebParam(name = "GetPopularKeywordsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPopularKeywordsRequest")
      GetPopularKeywordsRequestType getPopularKeywordsRequest);

  /**
   * 
   * @param getProductFamilyMembersRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetProductFamilyMembersResponseType
   */
  @WebMethod(operationName = "GetProductFamilyMembers")
  @WebResult(name = "GetProductFamilyMembersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductFamilyMembersResponse")
  public GetProductFamilyMembersResponseType getProductFamilyMembers(
      @WebParam(name = "GetProductFamilyMembersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductFamilyMembersRequest")
      GetProductFamilyMembersRequestType getProductFamilyMembersRequest);

  /**
   * 
   * @param getProductFinderRequest
   * @return returns ebay.apis.eblbasecomponents.GetProductFinderResponseType
   */
  @WebMethod(operationName = "GetProductFinder")
  @WebResult(name = "GetProductFinderResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductFinderResponse")
  public GetProductFinderResponseType getProductFinder(
      @WebParam(name = "GetProductFinderRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductFinderRequest")
      GetProductFinderRequestType getProductFinderRequest);

  /**
   * 
   * @param getProductFinderXSLRequest
   * @return returns ebay.apis.eblbasecomponents.GetProductFinderXSLResponseType
   */
  @WebMethod(operationName = "GetProductFinderXSL")
  @WebResult(name = "GetProductFinderXSLResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductFinderXSLResponse")
  public GetProductFinderXSLResponseType getProductFinderXSL(
      @WebParam(name = "GetProductFinderXSLRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductFinderXSLRequest")
      GetProductFinderXSLRequestType getProductFinderXSLRequest);

  /**
   * 
   * @param getProductSearchPageRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetProductSearchPageResponseType
   */
  @WebMethod(operationName = "GetProductSearchPage")
  @WebResult(name = "GetProductSearchPageResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductSearchPageResponse")
  public GetProductSearchPageResponseType getProductSearchPage(
      @WebParam(name = "GetProductSearchPageRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductSearchPageRequest")
      GetProductSearchPageRequestType getProductSearchPageRequest);

  /**
   * 
   * @param getProductSearchResultsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetProductSearchResultsResponseType
   */
  @WebMethod(operationName = "GetProductSearchResults")
  @WebResult(name = "GetProductSearchResultsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductSearchResultsResponse")
  public GetProductSearchResultsResponseType getProductSearchResults(
      @WebParam(name = "GetProductSearchResultsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductSearchResultsRequest")
      GetProductSearchResultsRequestType getProductSearchResultsRequest);

  /**
   * 
   * @param getProductSellingPagesRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetProductSellingPagesResponseType
   */
  @WebMethod(operationName = "GetProductSellingPages")
  @WebResult(name = "GetProductSellingPagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductSellingPagesResponse")
  public GetProductSellingPagesResponseType getProductSellingPages(
      @WebParam(name = "GetProductSellingPagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetProductSellingPagesRequest")
      GetProductSellingPagesRequestType getProductSellingPagesRequest);

  /**
   * 
   * @param getPromotionRulesRequest
   * @return returns ebay.apis.eblbasecomponents.GetPromotionRulesResponseType
   */
  @WebMethod(operationName = "GetPromotionRules")
  @WebResult(name = "GetPromotionRulesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPromotionRulesResponse")
  public GetPromotionRulesResponseType getPromotionRules(
      @WebParam(name = "GetPromotionRulesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetPromotionRulesRequest")
      GetPromotionRulesRequestType getPromotionRulesRequest);

  /**
   * 
   * @param getRecommendationsRequest
   * @return returns ebay.apis.eblbasecomponents.GetRecommendationsResponseType
   */
  @WebMethod(operationName = "GetRecommendations")
  @WebResult(name = "GetRecommendationsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetRecommendationsResponse")
  public GetRecommendationsResponseType getRecommendations(
      @WebParam(name = "GetRecommendationsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetRecommendationsRequest")
      GetRecommendationsRequestType getRecommendationsRequest);

  /**
   * 
   * @param getReturnURLRequest
   * @return returns ebay.apis.eblbasecomponents.GetReturnURLResponseType
   */
  @WebMethod(operationName = "GetReturnURL")
  @WebResult(name = "GetReturnURLResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetReturnURLResponse")
  public GetReturnURLResponseType getReturnURL(
      @WebParam(name = "GetReturnURLRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetReturnURLRequest")
      GetReturnURLRequestType getReturnURLRequest);

  /**
   * 
   * @param getRuNameRequest
   * @return returns ebay.apis.eblbasecomponents.GetRuNameResponseType
   */
  @WebMethod(operationName = "GetRuName")
  @WebResult(name = "GetRuNameResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetRuNameResponse")
  public GetRuNameResponseType getRuName(
      @WebParam(name = "GetRuNameRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetRuNameRequest")
      GetRuNameRequestType getRuNameRequest);

  /**
   * 
   * @param getSearchResultsRequest
   * @return returns ebay.apis.eblbasecomponents.GetSearchResultsResponseType
   */
  // ! <example xn="EBayAPIInterface_getSearchResults">
  // ! <c>chap09</c><s>soapclient</s>
  @WebMethod(operationName = "GetSearchResults")
  @WebResult(name = "GetSearchResultsResponse",
      targetNamespace = "urn:ebay:apis:eBLBaseComponents",
      partName = "GetSearchResultsResponse")
  public GetSearchResultsResponseType getSearchResults(
      @WebParam(name = "GetSearchResultsRequest",
          targetNamespace = "urn:ebay:apis:eBLBaseComponents",
          partName = "GetSearchResultsRequest")
      GetSearchResultsRequestType getSearchResultsRequest);
  // ! </example>

  /**
   * 
   * @param getSearchResultsExpressRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetSearchResultsExpressResponseType
   */
  @WebMethod(operationName = "GetSearchResultsExpress")
  @WebResult(name = "GetSearchResultsExpressResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSearchResultsExpressResponse")
  public GetSearchResultsExpressResponseType getSearchResultsExpress(
      @WebParam(name = "GetSearchResultsExpressRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSearchResultsExpressRequest")
      GetSearchResultsExpressRequestType getSearchResultsExpressRequest);

  /**
   * 
   * @param getSellerEventsRequest
   * @return returns ebay.apis.eblbasecomponents.GetSellerEventsResponseType
   */
  @WebMethod(operationName = "GetSellerEvents")
  @WebResult(name = "GetSellerEventsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerEventsResponse")
  public GetSellerEventsResponseType getSellerEvents(
      @WebParam(name = "GetSellerEventsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerEventsRequest")
      GetSellerEventsRequestType getSellerEventsRequest);

  /**
   * 
   * @param getSellerListRequest
   * @return returns ebay.apis.eblbasecomponents.GetSellerListResponseType
   */
  @WebMethod(operationName = "GetSellerList")
  @WebResult(name = "GetSellerListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerListResponse")
  public GetSellerListResponseType getSellerList(
      @WebParam(name = "GetSellerListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerListRequest")
      GetSellerListRequestType getSellerListRequest);

  /**
   * 
   * @param getSellerPaymentsRequest
   * @return returns ebay.apis.eblbasecomponents.GetSellerPaymentsResponseType
   */
  @WebMethod(operationName = "GetSellerPayments")
  @WebResult(name = "GetSellerPaymentsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerPaymentsResponse")
  public GetSellerPaymentsResponseType getSellerPayments(
      @WebParam(name = "GetSellerPaymentsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerPaymentsRequest")
      GetSellerPaymentsRequestType getSellerPaymentsRequest);

  /**
   * 
   * @param getSellerTransactionsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetSellerTransactionsResponseType
   */
  @WebMethod(operationName = "GetSellerTransactions")
  @WebResult(name = "GetSellerTransactionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerTransactionsResponse")
  public GetSellerTransactionsResponseType getSellerTransactions(
      @WebParam(name = "GetSellerTransactionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSellerTransactionsRequest")
      GetSellerTransactionsRequestType getSellerTransactionsRequest);

  /**
   * 
   * @param getStoreRequest
   * @return returns ebay.apis.eblbasecomponents.GetStoreResponseType
   */
  @WebMethod(operationName = "GetStore")
  @WebResult(name = "GetStoreResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreResponse")
  public GetStoreResponseType getStore(
      @WebParam(name = "GetStoreRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreRequest")
      GetStoreRequestType getStoreRequest);

  /**
   * 
   * @param getStoreCategoryUpdateStatusRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetStoreCategoryUpdateStatusResponseType
   */
  @WebMethod(operationName = "GetStoreCategoryUpdateStatus")
  @WebResult(name = "GetStoreCategoryUpdateStatusResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreCategoryUpdateStatusResponse")
  public GetStoreCategoryUpdateStatusResponseType getStoreCategoryUpdateStatus(
      @WebParam(name = "GetStoreCategoryUpdateStatusRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreCategoryUpdateStatusRequest")
      GetStoreCategoryUpdateStatusRequestType getStoreCategoryUpdateStatusRequest);

  /**
   * 
   * @param getStoreCustomPageRequest
   * @return returns ebay.apis.eblbasecomponents.GetStoreCustomPageResponseType
   */
  @WebMethod(operationName = "GetStoreCustomPage")
  @WebResult(name = "GetStoreCustomPageResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreCustomPageResponse")
  public GetStoreCustomPageResponseType getStoreCustomPage(
      @WebParam(name = "GetStoreCustomPageRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreCustomPageRequest")
      GetStoreCustomPageRequestType getStoreCustomPageRequest);

  /**
   * 
   * @param getStoreOptionsRequest
   * @return returns ebay.apis.eblbasecomponents.GetStoreOptionsResponseType
   */
  @WebMethod(operationName = "GetStoreOptions")
  @WebResult(name = "GetStoreOptionsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreOptionsResponse")
  public GetStoreOptionsResponseType getStoreOptions(
      @WebParam(name = "GetStoreOptionsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStoreOptionsRequest")
      GetStoreOptionsRequestType getStoreOptionsRequest);

  /**
   * 
   * @param getStorePreferencesRequest
   * @return returns ebay.apis.eblbasecomponents.GetStorePreferencesResponseType
   */
  @WebMethod(operationName = "GetStorePreferences")
  @WebResult(name = "GetStorePreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStorePreferencesResponse")
  public GetStorePreferencesResponseType getStorePreferences(
      @WebParam(name = "GetStorePreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetStorePreferencesRequest")
      GetStorePreferencesRequestType getStorePreferencesRequest);

  /**
   * 
   * @param getSuggestedCategoriesRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetSuggestedCategoriesResponseType
   */
  @WebMethod(operationName = "GetSuggestedCategories")
  @WebResult(name = "GetSuggestedCategoriesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSuggestedCategoriesResponse")
  public GetSuggestedCategoriesResponseType getSuggestedCategories(
      @WebParam(name = "GetSuggestedCategoriesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetSuggestedCategoriesRequest")
      GetSuggestedCategoriesRequestType getSuggestedCategoriesRequest);

  /**
   * 
   * @param getTaxTableRequest
   * @return returns ebay.apis.eblbasecomponents.GetTaxTableResponseType
   */
  @WebMethod(operationName = "GetTaxTable")
  @WebResult(name = "GetTaxTableResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetTaxTableResponse")
  public GetTaxTableResponseType getTaxTable(
      @WebParam(name = "GetTaxTableRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetTaxTableRequest")
      GetTaxTableRequestType getTaxTableRequest);

  /**
   * 
   * @param getUserRequest
   * @return returns ebay.apis.eblbasecomponents.GetUserResponseType
   */
  @WebMethod(operationName = "GetUser")
  @WebResult(name = "GetUserResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserResponse")
  public GetUserResponseType getUser(
      @WebParam(name = "GetUserRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserRequest")
      GetUserRequestType getUserRequest);

  /**
   * 
   * @param getUserContactDetailsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetUserContactDetailsResponseType
   */
  @WebMethod(operationName = "GetUserContactDetails")
  @WebResult(name = "GetUserContactDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserContactDetailsResponse")
  public GetUserContactDetailsResponseType getUserContactDetails(
      @WebParam(name = "GetUserContactDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserContactDetailsRequest")
      GetUserContactDetailsRequestType getUserContactDetailsRequest);

  /**
   * 
   * @param getUserDisputesRequest
   * @return returns ebay.apis.eblbasecomponents.GetUserDisputesResponseType
   */
  @WebMethod(operationName = "GetUserDisputes")
  @WebResult(name = "GetUserDisputesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserDisputesResponse")
  public GetUserDisputesResponseType getUserDisputes(
      @WebParam(name = "GetUserDisputesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserDisputesRequest")
      GetUserDisputesRequestType getUserDisputesRequest);

  /**
   * 
   * @param getUserPreferencesRequest
   * @return returns ebay.apis.eblbasecomponents.GetUserPreferencesResponseType
   */
  @WebMethod(operationName = "GetUserPreferences")
  @WebResult(name = "GetUserPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserPreferencesResponse")
  public GetUserPreferencesResponseType getUserPreferences(
      @WebParam(name = "GetUserPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetUserPreferencesRequest")
      GetUserPreferencesRequestType getUserPreferencesRequest);

  /**
   * 
   * @param getWantItNowPostRequest
   * @return returns ebay.apis.eblbasecomponents.GetWantItNowPostResponseType
   */
  @WebMethod(operationName = "GetWantItNowPost")
  @WebResult(name = "GetWantItNowPostResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetWantItNowPostResponse")
  public GetWantItNowPostResponseType getWantItNowPost(
      @WebParam(name = "GetWantItNowPostRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetWantItNowPostRequest")
      GetWantItNowPostRequestType getWantItNowPostRequest);

  /**
   * 
   * @param getWantItNowSearchResultsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.GetWantItNowSearchResultsResponseType
   */
  @WebMethod(operationName = "GetWantItNowSearchResults")
  @WebResult(name = "GetWantItNowSearchResultsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetWantItNowSearchResultsResponse")
  public GetWantItNowSearchResultsResponseType getWantItNowSearchResults(
      @WebParam(name = "GetWantItNowSearchResultsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GetWantItNowSearchResultsRequest")
      GetWantItNowSearchResultsRequestType getWantItNowSearchResultsRequest);

  /**
   * 
   * @param geteBayDetailsRequest
   * @return returns ebay.apis.eblbasecomponents.GeteBayDetailsResponseType
   */
  @WebMethod(operationName = "GeteBayDetails")
  @WebResult(name = "GeteBayDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayDetailsResponse")
  public GeteBayDetailsResponseType geteBayDetails(
      @WebParam(name = "GeteBayDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayDetailsRequest")
      GeteBayDetailsRequestType geteBayDetailsRequest);

  /**
   * 
   * @param geteBayOfficialTimeRequest
   * @return returns ebay.apis.eblbasecomponents.GeteBayOfficialTimeResponseType
   */
  @WebMethod(operationName = "GeteBayOfficialTime")
  @WebResult(name = "GeteBayOfficialTimeResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayOfficialTimeResponse")
  public GeteBayOfficialTimeResponseType geteBayOfficialTime(
      @WebParam(name = "GeteBayOfficialTimeRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "GeteBayOfficialTimeRequest")
      GeteBayOfficialTimeRequestType geteBayOfficialTimeRequest);

  /**
   * 
   * @param issueRefundRequest
   * @return returns ebay.apis.eblbasecomponents.IssueRefundResponseType
   */
  @WebMethod(operationName = "IssueRefund")
  @WebResult(name = "IssueRefundResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "IssueRefundResponse")
  public IssueRefundResponseType issueRefund(
      @WebParam(name = "IssueRefundRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "IssueRefundRequest")
      IssueRefundRequestType issueRefundRequest);

  /**
   * 
   * @param leaveFeedbackRequest
   * @return returns ebay.apis.eblbasecomponents.LeaveFeedbackResponseType
   */
  @WebMethod(operationName = "LeaveFeedback")
  @WebResult(name = "LeaveFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "LeaveFeedbackResponse")
  public LeaveFeedbackResponseType leaveFeedback(
      @WebParam(name = "LeaveFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "LeaveFeedbackRequest")
      LeaveFeedbackRequestType leaveFeedbackRequest);

  /**
   * 
   * @param placeOfferRequest
   * @return returns ebay.apis.eblbasecomponents.PlaceOfferResponseType
   */
  @WebMethod(operationName = "PlaceOffer")
  @WebResult(name = "PlaceOfferResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "PlaceOfferResponse")
  public PlaceOfferResponseType placeOffer(
      @WebParam(name = "PlaceOfferRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "PlaceOfferRequest")
      PlaceOfferRequestType placeOfferRequest);

  /**
   * 
   * @param relistItemRequest
   * @return returns ebay.apis.eblbasecomponents.RelistItemResponseType
   */
  @WebMethod(operationName = "RelistItem")
  @WebResult(name = "RelistItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RelistItemResponse")
  public RelistItemResponseType relistItem(
      @WebParam(name = "RelistItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RelistItemRequest")
      RelistItemRequestType relistItemRequest);

  /**
   * 
   * @param removeFromWatchListRequest
   * @return returns ebay.apis.eblbasecomponents.RemoveFromWatchListResponseType
   */
  @WebMethod(operationName = "RemoveFromWatchList")
  @WebResult(name = "RemoveFromWatchListResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RemoveFromWatchListResponse")
  public RemoveFromWatchListResponseType removeFromWatchList(
      @WebParam(name = "RemoveFromWatchListRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RemoveFromWatchListRequest")
      RemoveFromWatchListRequestType removeFromWatchListRequest);

  /**
   * 
   * @param respondToBestOfferRequest
   * @return returns ebay.apis.eblbasecomponents.RespondToBestOfferResponseType
   */
  @WebMethod(operationName = "RespondToBestOffer")
  @WebResult(name = "RespondToBestOfferResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToBestOfferResponse")
  public RespondToBestOfferResponseType respondToBestOffer(
      @WebParam(name = "RespondToBestOfferRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToBestOfferRequest")
      RespondToBestOfferRequestType respondToBestOfferRequest);

  /**
   * 
   * @param respondToFeedbackRequest
   * @return returns ebay.apis.eblbasecomponents.RespondToFeedbackResponseType
   */
  @WebMethod(operationName = "RespondToFeedback")
  @WebResult(name = "RespondToFeedbackResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToFeedbackResponse")
  public RespondToFeedbackResponseType respondToFeedback(
      @WebParam(name = "RespondToFeedbackRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToFeedbackRequest")
      RespondToFeedbackRequestType respondToFeedbackRequest);

  /**
   * 
   * @param respondToWantItNowPostRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.RespondToWantItNowPostResponseType
   */
  @WebMethod(operationName = "RespondToWantItNowPost")
  @WebResult(name = "RespondToWantItNowPostResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToWantItNowPostResponse")
  public RespondToWantItNowPostResponseType respondToWantItNowPost(
      @WebParam(name = "RespondToWantItNowPostRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "RespondToWantItNowPostRequest")
      RespondToWantItNowPostRequestType respondToWantItNowPostRequest);

  /**
   * 
   * @param reviseCheckoutStatusRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.ReviseCheckoutStatusResponseType
   */
  @WebMethod(operationName = "ReviseCheckoutStatus")
  @WebResult(name = "ReviseCheckoutStatusResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseCheckoutStatusResponse")
  public ReviseCheckoutStatusResponseType reviseCheckoutStatus(
      @WebParam(name = "ReviseCheckoutStatusRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseCheckoutStatusRequest")
      ReviseCheckoutStatusRequestType reviseCheckoutStatusRequest);

  /**
   * 
   * @param reviseItemRequest
   * @return returns ebay.apis.eblbasecomponents.ReviseItemResponseType
   */
  @WebMethod(operationName = "ReviseItem")
  @WebResult(name = "ReviseItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseItemResponse")
  public ReviseItemResponseType reviseItem(
      @WebParam(name = "ReviseItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseItemRequest")
      ReviseItemRequestType reviseItemRequest);

  /**
   * 
   * @param reviseLiveAuctionItemRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.ReviseLiveAuctionItemResponseType
   */
  @WebMethod(operationName = "ReviseLiveAuctionItem")
  @WebResult(name = "ReviseLiveAuctionItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseLiveAuctionItemResponse")
  public ReviseLiveAuctionItemResponseType reviseLiveAuctionItem(
      @WebParam(name = "ReviseLiveAuctionItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseLiveAuctionItemRequest")
      ReviseLiveAuctionItemRequestType reviseLiveAuctionItemRequest);

  /**
   * 
   * @param reviseMyMessagesRequest
   * @return returns ebay.apis.eblbasecomponents.ReviseMyMessagesResponseType
   */
  @WebMethod(operationName = "ReviseMyMessages")
  @WebResult(name = "ReviseMyMessagesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesResponse")
  public ReviseMyMessagesResponseType reviseMyMessages(
      @WebParam(name = "ReviseMyMessagesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesRequest")
      ReviseMyMessagesRequestType reviseMyMessagesRequest);

  /**
   * 
   * @param reviseMyMessagesFoldersRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.ReviseMyMessagesFoldersResponseType
   */
  @WebMethod(operationName = "ReviseMyMessagesFolders")
  @WebResult(name = "ReviseMyMessagesFoldersResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesFoldersResponse")
  public ReviseMyMessagesFoldersResponseType reviseMyMessagesFolders(
      @WebParam(name = "ReviseMyMessagesFoldersRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ReviseMyMessagesFoldersRequest")
      ReviseMyMessagesFoldersRequestType reviseMyMessagesFoldersRequest);

  /**
   * 
   * @param sellerReverseDisputeRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.SellerReverseDisputeResponseType
   */
  @WebMethod(operationName = "SellerReverseDispute")
  @WebResult(name = "SellerReverseDisputeResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SellerReverseDisputeResponse")
  public SellerReverseDisputeResponseType sellerReverseDispute(
      @WebParam(name = "SellerReverseDisputeRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SellerReverseDisputeRequest")
      SellerReverseDisputeRequestType sellerReverseDisputeRequest);

  /**
   * 
   * @param sendInvoiceRequest
   * @return returns ebay.apis.eblbasecomponents.SendInvoiceResponseType
   */
  @WebMethod(operationName = "SendInvoice")
  @WebResult(name = "SendInvoiceResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SendInvoiceResponse")
  public SendInvoiceResponseType sendInvoice(
      @WebParam(name = "SendInvoiceRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SendInvoiceRequest")
      SendInvoiceRequestType sendInvoiceRequest);

  /**
   * 
   * @param setNotificationPreferencesRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.SetNotificationPreferencesResponseType
   */
  @WebMethod(operationName = "SetNotificationPreferences")
  @WebResult(name = "SetNotificationPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetNotificationPreferencesResponse")
  public SetNotificationPreferencesResponseType setNotificationPreferences(
      @WebParam(name = "SetNotificationPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetNotificationPreferencesRequest")
      SetNotificationPreferencesRequestType setNotificationPreferencesRequest);

  /**
   * 
   * @param setPictureManagerDetailsRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.SetPictureManagerDetailsResponseType
   */
  @WebMethod(operationName = "SetPictureManagerDetails")
  @WebResult(name = "SetPictureManagerDetailsResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetPictureManagerDetailsResponse")
  public SetPictureManagerDetailsResponseType setPictureManagerDetails(
      @WebParam(name = "SetPictureManagerDetailsRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetPictureManagerDetailsRequest")
      SetPictureManagerDetailsRequestType setPictureManagerDetailsRequest);

  /**
   * 
   * @param setPromotionRulesRequest
   * @return returns ebay.apis.eblbasecomponents.SetPromotionRulesResponseType
   */
  @WebMethod(operationName = "SetPromotionRules")
  @WebResult(name = "SetPromotionRulesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetPromotionRulesResponse")
  public SetPromotionRulesResponseType setPromotionRules(
      @WebParam(name = "SetPromotionRulesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetPromotionRulesRequest")
      SetPromotionRulesRequestType setPromotionRulesRequest);

  /**
   * 
   * @param setReturnURLRequest
   * @return returns ebay.apis.eblbasecomponents.SetReturnURLResponseType
   */
  @WebMethod(operationName = "SetReturnURL")
  @WebResult(name = "SetReturnURLResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetReturnURLResponse")
  public SetReturnURLResponseType setReturnURL(
      @WebParam(name = "SetReturnURLRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetReturnURLRequest")
      SetReturnURLRequestType setReturnURLRequest);

  /**
   * 
   * @param setStoreRequest
   * @return returns ebay.apis.eblbasecomponents.SetStoreResponseType
   */
  @WebMethod(operationName = "SetStore")
  @WebResult(name = "SetStoreResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreResponse")
  public SetStoreResponseType setStore(
      @WebParam(name = "SetStoreRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreRequest")
      SetStoreRequestType setStoreRequest);

  /**
   * 
   * @param setStoreCategoriesRequest
   * @return returns ebay.apis.eblbasecomponents.SetStoreCategoriesResponseType
   */
  @WebMethod(operationName = "SetStoreCategories")
  @WebResult(name = "SetStoreCategoriesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreCategoriesResponse")
  public SetStoreCategoriesResponseType setStoreCategories(
      @WebParam(name = "SetStoreCategoriesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreCategoriesRequest")
      SetStoreCategoriesRequestType setStoreCategoriesRequest);

  /**
   * 
   * @param setStoreCustomPageRequest
   * @return returns ebay.apis.eblbasecomponents.SetStoreCustomPageResponseType
   */
  @WebMethod(operationName = "SetStoreCustomPage")
  @WebResult(name = "SetStoreCustomPageResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreCustomPageResponse")
  public SetStoreCustomPageResponseType setStoreCustomPage(
      @WebParam(name = "SetStoreCustomPageRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStoreCustomPageRequest")
      SetStoreCustomPageRequestType setStoreCustomPageRequest);

  /**
   * 
   * @param setStorePreferencesRequest
   * @return returns ebay.apis.eblbasecomponents.SetStorePreferencesResponseType
   */
  @WebMethod(operationName = "SetStorePreferences")
  @WebResult(name = "SetStorePreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStorePreferencesResponse")
  public SetStorePreferencesResponseType setStorePreferences(
      @WebParam(name = "SetStorePreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetStorePreferencesRequest")
      SetStorePreferencesRequestType setStorePreferencesRequest);

  /**
   * 
   * @param setTaxTableRequest
   * @return returns ebay.apis.eblbasecomponents.SetTaxTableResponseType
   */
  @WebMethod(operationName = "SetTaxTable")
  @WebResult(name = "SetTaxTableResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetTaxTableResponse")
  public SetTaxTableResponseType setTaxTable(
      @WebParam(name = "SetTaxTableRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetTaxTableRequest")
      SetTaxTableRequestType setTaxTableRequest);

  /**
   * 
   * @param setUserNotesRequest
   * @return returns ebay.apis.eblbasecomponents.SetUserNotesResponseType
   */
  @WebMethod(operationName = "SetUserNotes")
  @WebResult(name = "SetUserNotesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserNotesResponse")
  public SetUserNotesResponseType setUserNotes(
      @WebParam(name = "SetUserNotesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserNotesRequest")
      SetUserNotesRequestType setUserNotesRequest);

  /**
   * 
   * @param setUserPreferencesRequest
   * @return returns ebay.apis.eblbasecomponents.SetUserPreferencesResponseType
   */
  @WebMethod(operationName = "SetUserPreferences")
  @WebResult(name = "SetUserPreferencesResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserPreferencesResponse")
  public SetUserPreferencesResponseType setUserPreferences(
      @WebParam(name = "SetUserPreferencesRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "SetUserPreferencesRequest")
      SetUserPreferencesRequestType setUserPreferencesRequest);

  /**
   * 
   * @param validateChallengeInputRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.ValidateChallengeInputResponseType
   */
  @WebMethod(operationName = "ValidateChallengeInput")
  @WebResult(name = "ValidateChallengeInputResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateChallengeInputResponse")
  public ValidateChallengeInputResponseType validateChallengeInput(
      @WebParam(name = "ValidateChallengeInputRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateChallengeInputRequest")
      ValidateChallengeInputRequestType validateChallengeInputRequest);

  /**
   * 
   * @param validateTestUserRegistrationRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.ValidateTestUserRegistrationResponseType
   */
  @WebMethod(operationName = "ValidateTestUserRegistration")
  @WebResult(name = "ValidateTestUserRegistrationResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateTestUserRegistrationResponse")
  public ValidateTestUserRegistrationResponseType validateTestUserRegistration(
      @WebParam(name = "ValidateTestUserRegistrationRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "ValidateTestUserRegistrationRequest")
      ValidateTestUserRegistrationRequestType validateTestUserRegistrationRequest);

  /**
   * 
   * @param verifyAddItemRequest
   * @return returns ebay.apis.eblbasecomponents.VerifyAddItemResponseType
   */
  @WebMethod(operationName = "VerifyAddItem")
  @WebResult(name = "VerifyAddItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddItemResponse")
  public VerifyAddItemResponseType verifyAddItem(
      @WebParam(name = "VerifyAddItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddItemRequest")
      VerifyAddItemRequestType verifyAddItemRequest);

  /**
   * 
   * @param verifyAddSecondChanceItemRequest
   * @return returns
   *         ebay.apis.eblbasecomponents.VerifyAddSecondChanceItemResponseType
   */
  @WebMethod(operationName = "VerifyAddSecondChanceItem")
  @WebResult(name = "VerifyAddSecondChanceItemResponse", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddSecondChanceItemResponse")
  public VerifyAddSecondChanceItemResponseType verifyAddSecondChanceItem(
      @WebParam(name = "VerifyAddSecondChanceItemRequest", targetNamespace = "urn:ebay:apis:eBLBaseComponents", partName = "VerifyAddSecondChanceItemRequest")
      VerifyAddSecondChanceItemRequestType verifyAddSecondChanceItemRequest);

}
