/*
* Copyright 2006-2007 Javector Software LLC
*
* Licensed under the GNU General Public License, Version 2 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.gnu.org/copyleft/gpl.html
*
* THE SOURCE CODE AND ACCOMPANYING FILES ARE PROVIDED WITHOUT ANY WARRANTY,
* WRITTEN OR IMPLIED.
*
* The copyright holder provides this software under other licenses for those
* wishing to include it with products or systems not licensed under the GPL.
* Contact licenses@javector.com for more information.
*/
package com.soabook.soashopper;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.example.retail.CategoryType;
import com.example.retail.OfferType;
import com.example.retail.PriceType;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.1-hudson-1368-EA3
 * Generated source version: 2.1
 * 
 */
//! <example xn="ShopperPort">
//! <c>chap09</c><s>wsdl</s>
@WebService(name = "ShopperPort",
  targetNamespace = "http://soabook.com/soashopper")
@XmlSeeAlso( { com.example.faults.ObjectFactory.class,
    com.soabook.soashopper.ObjectFactory.class,
    com.example.retail.ObjectFactory.class })
public interface ShopperPort {

  @WebMethod
  @WebResult(name = "offer", targetNamespace = "http://www.example.com/retail")
  @RequestWrapper(localName = "offerSearch", 
    targetNamespace = "http://soabook.com/soashopper",
    className = "com.soabook.soashopper.OfferSearch")
  @ResponseWrapper(localName = "offerSearchReturn",
    targetNamespace = "http://soabook.com/soashopper", 
    className = "com.soabook.soashopper.OfferSearchReturn")
  public List<OfferType> offerSearch(
      @WebParam(name = "keywords", 
        targetNamespace = "http://soabook.com/soashopper")
      String keywords,
      @WebParam(name = "category", 
        targetNamespace = "http://soabook.com/soashopper")
      CategoryType category,
      @WebParam(name = "lowprice", 
        targetNamespace = "http://soabook.com/soashopper")
      PriceType lowprice,
      @WebParam(name = "highprice", 
        targetNamespace = "http://soabook.com/soashopper")
      PriceType highprice) throws InputFault;

}
//! </example>
