/*
* Copyright 2006 Javector Software LLC
*
* Licensed under the GNU General Public License, Version 2 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.gnu.org/copyleft/gpl.html
*
* THE SOURCE CODE AND ACCOMPANYING FILES ARE PROVIDED WITHOUT ANY WARRANTY,
* WRITTEN OR IMPLIED.
*
* The copyright holder provides this software under other licenses for those
* wishing to include it with products or systems not licensed under the GPL.
* Contact licenses@javector.com for more information.
*/

package com.example.req;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.example.oms.BUSOBJCCARD;
import com.example.oms.BUSOBJITEM;
import com.example.oms.OrderType;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b02-ea3
 * Generated source version: 2.0
 * 
 */
//! <example xn="SEI_DEFINITION">
//! <c>chap07</c><s>sei</s>
@WebService(name = "RequestOrderPort", 
    targetNamespace = "http://www.example.com/req", 
    wsdlLocation = "WEB-INF/wsdl/RequestOrder.wsdl")
public interface RequestOrderPort {

    @WebMethod
    @WebResult(name = "Order", targetNamespace = "http://www.example.com/oms")
    @RequestWrapper(localName = "requestOrder", 
        targetNamespace = "http://www.example.com/req", 
        className = "com.example.req.RequestOrder")
    @ResponseWrapper(localName = "requestOrderResponse", 
        targetNamespace = "http://www.example.com/req", 
        className = "com.example.req.RequestOrderResponse")
    public OrderType requestOrder(
        @WebParam(name = "CUST_NO", 
            targetNamespace = "http://www.example.com/req")
        String custNO,
        @WebParam(name = "PURCH_ORD_NO", 
            targetNamespace = "http://www.example.com/req")
        String purchORDNO,
        @WebParam(name = "ccard", 
            targetNamespace = "http://www.example.com/req")
        BUSOBJCCARD ccard,
        @WebParam(name = "item", targetNamespace = "http://www.example.com/req")
        List<BUSOBJITEM> item)
        throws InputFault
    ;

}
//! </example> 
